
const product =[
    {
        id: 1,
        modelo: "GTX1030",
        precio: 100000,
        img: "./img/placa1.jpg",
        cantidad: 1,
    },
    {
        id: 2,
        modelo: "GTX4070", 
        precio: 150000,
        img: "./img/placa2.jpg",
        cantidad: 1,
    },
    {
        id: 3,
        modelo: "GTX 1660 Super",
        precio: 250000,
        img: "./img/placa3.jpg",
        cantidad: 1,
    },
    {
        id: 4,
        modelo: "RX580",
        precio: 80000,
        img: "./img/rx580.jpg",
        cantidad: 1,
    },
    {
        id: 5,
        modelo: "Fuente EVGA 600BR",
        precio: 80000,
        img: "./img/evga600.jpg",
        cantidad: 1,
    },
    {
        id: 6,
        modelo: "Fuente EVGA 500",
        precio: 70000,
        img: "./img/evga500.jpg",
        cantidad: 1,
    },
    {
        id: 7,
        modelo: "Fuente Corsair 500W",
        precio: 68000,
        img: "./img/crosair500.jpg",
        cantidad: 1,
    },
    {
        id: 8,
        modelo: "Fuente GigaByte P650B ",
        precio: 82000,
        img: "./img/gigap650.jpg",
        cantidad: 1,
    },
    {
        id: 9,
        modelo: "Fuente CoolerMaster 650W",
        precio: 76000,
        img: "./img/colermaster650.jpg",
        cantidad: 1,
    },
    {
        id: 10,
        modelo: "Fuente Aureox 600W",
        precio: 69000,
        img: "./img/aureox600.jpg",
        cantidad: 1,
    },
];